<?php

namespace App\Services;

use App\Models\NotificationTemplate;
use Barryvdh\DomPDF\Facade\Pdf as PDF;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;

class PdfExportService
{
    /**
     * Generate a PDF report using configurable templates
     */
    public function generateReport($templateName, $data, $options = [])
    {
        try {
            // Get template from database or use default
            $template = NotificationTemplate::where('name', $templateName)
                ->where('type', 'pdf_report')
                ->first();

            $htmlContent = $this->prepareTemplateContent($template, $data, $options);
            
            $pdf = PDF::loadHTML($htmlContent);
            
            // Set PDF options
            if (isset($options['orientation'])) {
                $pdf->setOrientation($options['orientation']);
            }
            
            if (isset($options['format'])) {
                $pdf->setPaper($options['format'], $options['orientation'] ?? 'portrait');
            }
            
            return $pdf;
        } catch (\Exception $e) {
            \Log::error('PDF Generation Failed: ' . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Prepare template content with dynamic data
     */
    private function prepareTemplateContent($template, $data, $options)
    {
        $templateContent = $this->getDefaultTemplate();
        
        if ($template && !empty($template->content)) {
            $templateContent = $template->content;
        }

        // Process template variables
        $processedContent = $this->processTemplateVariables($templateContent, $data, $options);

        // Apply header and footer if configured
        $processedContent = $this->applyHeaderFooter($processedContent, $options);

        return $processedContent;
    }

    /**
     * Process template variables and replace with actual data
     */
    private function processTemplateVariables($templateContent, $data, $options)
    {
        // Replace common variables
        $replacements = [
            '{{company_name}}' => $options['company_name'] ?? config('app.name', 'School Management System'),
            '{{report_title}}' => $options['title'] ?? 'Biometric Report',
            '{{generated_date}}' => Carbon::now()->format('d/m/Y H:i'),
            '{{logo_url}}' => $options['logo_url'] ?? asset('images/logo.png'),
            '{{signature_url}}' => $options['signature_url'] ?? '',
            '{{footer_text}}' => $options['footer_text'] ?? 'Generated by School Management System',
        ];

        foreach ($replacements as $placeholder => $value) {
            $templateContent = str_replace($placeholder, $value, $templateContent);
        }

        // Process data arrays
        $templateContent = $this->processDataArrays($templateContent, $data);

        return $templateContent;
    }

    /**
     * Process data arrays in template
     */
    private function processDataArrays($templateContent, $data)
    {
        // Handle table data
        if (isset($data['table_data']) && is_array($data['table_data'])) {
            $tableHtml = '<table class="table table-bordered">';
            
            // Headers
            if (!empty($data['table_data'][0])) {
                $tableHtml .= '<thead><tr>';
                foreach (array_keys($data['table_data'][0]) as $header) {
                    $tableHtml .= '<th>' . ucfirst(str_replace('_', ' ', $header)) . '</th>';
                }
                $tableHtml .= '</tr></thead>';
            }
            
            // Body
            $tableHtml .= '<tbody>';
            foreach ($data['table_data'] as $row) {
                $tableHtml .= '<tr>';
                foreach ($row as $cell) {
                    $tableHtml .= '<td>' . $cell . '</td>';
                }
                $tableHtml .= '</tr>';
            }
            $tableHtml .= '</tbody></table>';
            
            $templateContent = str_replace('{{table_data}}', $tableHtml, $templateContent);
        }

        // Handle chart data
        if (isset($data['chart_data'])) {
            $chartHtml = $this->generateChartHtml($data['chart_data']);
            $templateContent = str_replace('{{chart_data}}', $chartHtml, $templateContent);
        }

        // Handle summary data
        if (isset($data['summary'])) {
            $summaryHtml = '';
            foreach ($data['summary'] as $key => $value) {
                $summaryHtml .= '<div class="summary-item"><strong>' . ucfirst(str_replace('_', ' ', $key)) . ':</strong> ' . $value . '</div>';
            }
            $templateContent = str_replace('{{summary_data}}', $summaryHtml, $templateContent);
        }

        return $templateContent;
    }

    /**
     * Generate HTML for charts
     */
    private function generateChartHtml($chartData)
    {
        $chartHtml = '<div class="chart-container">';
        
        foreach ($chartData as $chart) {
            $chartHtml .= '<div class="chart-item">';
            $chartHtml .= '<h4>' . $chart['title'] ?? 'Chart' . '</h4>';
            
            if ($chart['type'] === 'bar') {
                $chartHtml .= $this->generateBarChart($chart['data']);
            } elseif ($chart['type'] === 'line') {
                $chartHtml .= $this->generateLineChart($chart['data']);
            } elseif ($chart['type'] === 'pie') {
                $chartHtml .= $this->generatePieChart($chart['data']);
            }
            
            $chartHtml .= '</div>';
        }
        
        $chartHtml .= '</div>';
        
        return $chartHtml;
    }

    /**
     * Generate bar chart HTML
     */
    private function generateBarChart($data)
    {
        $chartHtml = '<div class="bar-chart">';
        $maxValue = max(array_values($data));
        
        foreach ($data as $label => $value) {
            $percentage = $maxValue > 0 ? ($value / $maxValue) * 100 : 0;
            $chartHtml .= '<div class="bar-item">';
            $chartHtml .= '<span class="label">' . $label . '</span>';
            $chartHtml .= '<div class="bar-container">';
            $chartHtml .= '<div class="bar" style="width: ' . $percentage . '%;">' . $value . '</div>';
            $chartHtml .= '</div>';
            $chartHtml .= '</div>';
        }
        
        $chartHtml .= '</div>';
        
        return $chartHtml;
    }

    /**
     * Generate line chart HTML
     */
    private function generateLineChart($data)
    {
        $chartHtml = '<div class="line-chart">';

        // For simplicity, render as a simple line representation
        $chartHtml .= '<div class="line-data">';
        $chartHtml .= '<pre>';
        $maxValue = max(array_values($data));
        
        foreach ($data as $label => $value) {
            $barLength = $maxValue > 0 ? intval(($value / $maxValue) * 20) : 0;
            $bars = str_repeat('█', $barLength);
            $chartHtml .= sprintf("%-15s %s (%d)\n", $label, $bars, $value);
        }
        
        $chartHtml .= '</pre>';
        $chartHtml .= '</div>';
        $chartHtml .= '</div>';
        
        return $chartHtml;
    }

    /**
     * Generate pie chart HTML (as percentage breakdown)
     */
    private function generatePieChart($data)
    {
        $chartHtml = '<div class="pie-chart">';
        $total = array_sum($data);
        
        foreach ($data as $label => $value) {
            $percentage = $total > 0 ? ($value / $total) * 100 : 0;
            $chartHtml .= '<div class="pie-slice">';
            $chartHtml .= '<span class="label">' . $label . '</span>';
            $chartHtml .= '<span class="percentage">' . round($percentage, 2) . '%</span>';
            $chartHtml .= '<span class="value">(' . $value . ')</span>';
            $chartHtml .= '</div>';
        }
        
        $chartHtml .= '</div>';
        
        return $chartHtml;
    }

    /**
     * Apply header and footer to template
     */
    private function applyHeaderFooter($content, $options)
    {
        $header = $this->generateHeader($options);
        $footer = $this->generateFooter($options);
        
        return $header . $content . $footer;
    }

    /**
     * Generate header HTML
     */
    private function generateHeader($options)
    {
        $header = '<div class="pdf-header">';
        $header .= '<table width="100%" style="border-bottom: 2px solid #333; padding-bottom: 10px;">';
        $header .= '<tr>';
        
        if (isset($options['logo_url'])) {
            $header .= '<td width="20%"><img src="' . $options['logo_url'] . '" height="60" /></td>';
        }
        
        $header .= '<td width="60%" align="center">';
        $header .= '<h1 style="margin: 0; color: #333;">' . ($options['title'] ?? 'Report') . '</h1>';
        $header .= '<p style="margin: 5px 0 0 0; color: #666; font-size: 14px;">' . ($options['subtitle'] ?? '') . '</p>';
        $header .= '</td>';
        
        $header .= '<td width="20%" align="right" style="font-size: 12px; color: #666;">';
        $header .= 'Page: {{page}}</br>';
        $header .= 'Date: ' . Carbon::now()->format('d/m/Y') . '</br>';
        $header .= '</td>';
        
        $header .= '</tr>';
        $header .= '</table>';
        $header .= '</div>';
        
        return $header;
    }

    /**
     * Generate footer HTML
     */
    private function generateFooter($options)
    {
        $footer = '<div class="pdf-footer" style="position: fixed; bottom: 0; width: 100%; border-top: 1px solid #ccc; padding: 10px 0; font-size: 10px; color: #666;">';
        $footer .= '<table width="100%">';
        $footer .= '<tr>';
        $footer .= '<td width="33%">' . ($options['footer_left'] ?? $options['footer_text'] ?? 'Confidential') . '</td>';
        $footer .= '<td width="34%" align="center">Page {{page}} of {{ totalPages }}</td>';
        $footer .= '<td width="33%" align="right">' . ($options['footer_right'] ?? 'School Management System') . '</td>';
        $footer .= '</tr>';
        $footer .= '</table>';
        $footer .= '</div>';
        
        return $footer;
    }

    /**
     * Get default template if no custom template exists
     */
    private function getDefaultTemplate()
    {
        return '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{{report_title}}</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                .table th { background-color: #f2f2f2; }
                .summary-item { margin: 5px 0; }
                .chart-container { margin: 20px 0; }
                .bar-chart, .line-chart, .pie-chart { margin: 10px 0; }
                .bar-item { margin: 5px 0; }
                .bar-container { background: #eee; height: 20px; border-radius: 3px; overflow: hidden; }
                .bar { background: #007bff; height: 100%; display: flex; align-items: center; justify-content: center; color: white; font-size: 12px; }
            </style>
        </head>
        <body>
            {{{content}}}
        </body>
        </html>
        ';
    }

    /**
     * Export teacher biometric attendance report
     */
    public function exportTeacherAttendanceReport($teacherId, $startDate, $endDate, $options = [])
    {
        $data = [
            'summary' => [
                'teacher_name' => 'John Doe', // This would be populated from DB
                'department' => 'Mathematics',
                'total_working_days' => 22,
                'days_present' => 20,
                'days_absent' => 2,
                'late_arrivals' => 3,
                'early_departures' => 1,
                'attendance_percentage' => '90.91%'
            ],
            'table_data' => [
                ['date' => '2024-01-01', 'first_punch' => '08:45', 'last_punch' => '17:15', 'status' => 'On Time'],
                ['date' => '2024-01-02', 'first_punch' => '09:15', 'last_punch' => '16:45', 'status' => 'Late Arrival'],
                // More data would be populated from DB
            ],
            'chart_data' => [
                [
                    'type' => 'bar',
                    'title' => 'Monthly Attendance Trend',
                    'data' => ['Week 1' => 5, 'Week 2' => 4, 'Week 3' => 5, 'Week 4' => 5]
                ]
            ]
        ];

        $options = array_merge([
            'title' => 'Teacher Biometric Attendance Report',
            'subtitle' => 'Attendance Summary for Period: ' . $startDate . ' to ' . $endDate,
        ], $options);

        return $this->generateReport('teacher_attendance_pdf', $data, $options);
    }

    /**
     * Export department-wise performance report
     */
    public function exportDepartmentPerformanceReport($department, $startDate, $endDate, $options = [])
    {
        $data = [
            'summary' => [
                'department' => $department,
                'total_teachers' => 15,
                'average_attendance' => '89.5%',
                'average_punctuality' => '85.2%',
                'average_discipline' => '87.8%'
            ],
            'table_data' => [
                ['teacher_name' => 'John Doe', 'attendance' => '92%', 'punctuality' => '88%', 'discipline' => '90%'],
                ['teacher_name' => 'Jane Smith', 'attendance' => '87%', 'punctuality' => '82%', 'discipline' => '85%'],
                // More data would be populated from DB
            ]
        ];

        $options = array_merge([
            'title' => 'Department Performance Report',
            'subtitle' => 'Performance Summary for ' . $department . ': ' . $startDate . ' to ' . $endDate,
        ], $options);

        return $this->generateReport('department_performance_pdf', $data, $options);
    }

    /**
     * Export overall biometric analytics report
     */
    public function exportBiometricAnalyticsReport($startDate, $endDate, $options = [])
    {
        $data = [
            'summary' => [
                'total_teachers' => 50,
                'total_punches' => 1250,
                'average_attendance_rate' => '88.5%',
                'late_arrival_percentage' => '12.3%',
                'early_departure_percentage' => '8.7%'
            ],
            'chart_data' => [
                [
                    'type' => 'pie',
                    'title' => 'Attendance Distribution',
                    'data' => ['Present' => 88, 'Absent' => 12]
                ],
                [
                    'type' => 'line',
                    'title' => 'Daily Punch Trends',
                    'data' => ['Mon' => 180, 'Tue' => 195, 'Wed' => 175, 'Thu' => 200, 'Fri' => 185]
                ]
            ]
        ];

        $options = array_merge([
            'title' => 'Biometric Analytics Report',
            'subtitle' => 'Comprehensive Analytics for Period: ' . $startDate . ' to ' . $endDate,
        ], $options);

        return $this->generateReport('biometric_analytics_pdf', $data, $options);
    }
}