@extends('layouts.admin')

@section('title', 'Admit Card Management')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>Admit Card Management</h4>
                    <a href="{{ route('admin.admit-cards.create') }}" class="btn btn-primary">Generate Admit Cards</a>
                </div>
                <div class="card-body">
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form method="GET" class="mb-3">
                        <div class="row">
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="search" placeholder="Search students..." value="{{ request('search') }}">
                            </div>
                            <div class="col-md-2">
                                <select name="status" class="form-control">
                                    <option value="">All Statuses</option>
                                    <option value="draft" {{ request('status') == 'draft' ? 'selected' : '' }}>Draft</option>
                                    <option value="published" {{ request('status') == 'published' ? 'selected' : '' }}>Published</option>
                                    <option value="locked" {{ request('status') == 'locked' ? 'selected' : '' }}>Locked</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary">Filter</button>
                            </div>
                        </div>
                    </form>

                    <!-- Dues Enforcement Actions -->
                    <div class="mb-3 d-flex justify-content-between align-items-center bg-light p-3 border rounded">
                        <div class="text-muted small">
                            <i class="bi bi-info-circle"></i> <strong>Defaulter Policy:</strong> Students with outstanding fees will be blocked from downloading/printing admit cards on their portals.
                        </div>
                        <div>
                            <form action="{{ route('admin.admit-cards.block-defaulters') }}" method="POST" style="display: inline-block;">
                                @csrf
                                <button type="submit" class="btn btn-outline-danger btn-sm me-2" onclick="return confirm('Are you sure you want to revoke/block admit cards for ALL students with pending fees?')">
                                    <i class="bi bi-shield-lock"></i> Block All Fee Defaulters
                                </button>
                            </form>
                            <form action="{{ route('admin.admit-cards.unblock-cleared') }}" method="POST" style="display: inline-block;">
                                @csrf
                                <button type="submit" class="btn btn-outline-success btn-sm" onclick="return confirm('Are you sure you want to publish/unblock admit cards for ALL students who have no pending fees?')">
                                    <i class="bi bi-shield-check"></i> Unblock All Cleared Students
                                </button>
                            </form>
                        </div>
                    </div>

                    <form id="bulkActionForm" method="POST" action="">
                        @csrf
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered align-middle">
                                <thead>
                                    <tr>
                                        <th><input type="checkbox" id="selectAll"></th>
                                        <th>ID</th>
                                        <th>Photo</th>
                                        <th>Student</th>
                                        <th>Exam</th>
                                        <th>Class</th>
                                        <th>Outstanding Dues</th>
                                        <th>Status</th>
                                        <th>Generated By</th>
                                        <th>Published At</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($admitCards as $admitCard)
                                    @php
                                        $outstandingFees = $admitCard->student ? $admitCard->student->fees()->where('status', 'pending')->sum('due_amount') : 0;
                                    @endphp
                                    <tr>
                                        <td><input type="checkbox" name="ids[]" value="{{ $admitCard->id }}"></td>
                                        <td>{{ $admitCard->id }}</td>
                                        <td>
                                            <img src="{{ $admitCard->student->photo_url ?? asset('images/default-avatar.png') }}" alt="{{ $admitCard->student->name ?? '' }}"
                                                 class="rounded-circle" width="36" height="36" style="object-fit: cover;">
                                        </td>
                                        <td>{{ $admitCard->student->name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->exam->name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->student->class ?? 'N/A' }}</td>
                                        <td>
                                            @if($outstandingFees > 0)
                                                <span class="badge bg-danger">Defaulter (₹{{ number_format($outstandingFees, 2) }})</span>
                                            @else
                                                <span class="badge bg-success">No Dues</span>
                                            @endif
                                        </td>
                                        <td>
                                            <span class="badge bg-{{ $admitCard->status == 'draft' ? 'secondary' : ($admitCard->status == 'published' ? 'success' : ($admitCard->status == 'locked' ? 'primary' : 'danger')) }}">
                                                {{ ucfirst($admitCard->status) }}
                                            </span>
                                        </td>
                                        <td>{{ $admitCard->generator->name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->published_at ? $admitCard->published_at->format('d M Y h:i A') : 'N/A' }}</td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a href="{{ route('admin.admit-cards.preview', $admitCard) }}" class="btn btn-info text-white">Preview</a>
                                                @if($admitCard->status === 'draft')
                                                    <a href="{{ route('admin.admit-cards.publish', $admitCard) }}" class="btn btn-success" onclick="return confirm('Are you sure you want to publish this admit card?')">Publish</a>
                                                @elseif($admitCard->status === 'published')
                                                    <a href="{{ route('admin.admit-cards.lock', $admitCard) }}" class="btn btn-warning text-white" onclick="return confirm('Are you sure you want to lock this admit card?')">Lock</a>
                                                    <a href="{{ route('admin.admit-cards.revoke', $admitCard) }}" class="btn btn-danger" onclick="return confirm('Are you sure you want to revoke this admit card?')">Revoke</a>
                                                @elseif($admitCard->status === 'locked')
                                                    <a href="{{ route('admin.admit-cards.revoke', $admitCard) }}" class="btn btn-danger" onclick="return confirm('Are you sure you want to revoke this admit card?')">Revoke</a>
                                                @elseif($admitCard->status === 'revoked')
                                                    <a href="{{ route('admin.admit-cards.publish', $admitCard) }}" class="btn btn-success" onclick="return confirm('Are you sure you want to republish/unblock this admit card?')">Unblock</a>
                                                @endif
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="11" class="text-center">No admit cards found.</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>

                        @if(count($admitCards) > 0)
                        <div class="mt-3">
                            <button type="button" class="btn btn-success me-2" onclick="submitBulk('{{ route('admin.admit-cards.bulk-publish') }}', 'Are you sure you want to publish selected admit cards?')">Bulk Publish</button>
                            <button type="button" class="btn btn-warning me-2 text-white" onclick="submitBulk('{{ route('admin.admit-cards.bulk-lock') }}', 'Are you sure you want to lock selected admit cards?')">Bulk Lock</button>
                            <button type="button" class="btn btn-danger" onclick="submitBulk('{{ route('admin.admit-cards.bulk-revoke') }}', 'Are you sure you want to revoke/block selected admit cards?')">Bulk Revoke</button>
                        </div>
                        @endif
                    </form>

                    <div class="mt-4">
                        {{ $admitCards->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.getElementById('selectAll').addEventListener('click', function() {
    const checkboxes = document.querySelectorAll('input[name="ids[]"]');
    checkboxes.forEach(checkbox => checkbox.checked = this.checked);
});

function submitBulk(actionUrl, confirmMessage) {
    const checkboxes = document.querySelectorAll('input[name="ids[]"]:checked');
    if (checkboxes.length === 0) {
        alert('Please select at least one admit card to perform this action.');
        return;
    }
    if (confirm(confirmMessage)) {
        const form = document.getElementById('bulkActionForm');
        form.action = actionUrl;
        form.submit();
    }
}
</script>
@endsection
