@extends('layouts.admin')

@section('title', 'Admit Card Management')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>Admit Card Management</h4>
                    <a href="{{ route('admin.admit-cards.create') }}" class="btn btn-primary">Generate Admit Cards</a>
                </div>
                <div class="card-body">
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form method="GET" class="mb-3">
                        <div class="row">
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="search" placeholder="Search students..." value="{{ request('search') }}">
                            </div>
                            <div class="col-md-2">
                                <select name="status" class="form-control">
                                    <option value="">All Statuses</option>
                                    <option value="draft" {{ request('status') == 'draft' ? 'selected' : '' }}>Draft</option>
                                    <option value="published" {{ request('status') == 'published' ? 'selected' : '' }}>Published</option>
                                    <option value="locked" {{ request('status') == 'locked' ? 'selected' : '' }}>Locked</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-primary">Filter</button>
                            </div>
                        </div>
                    </form>

                    <form method="POST" action="{{ route('admin.admit-cards.bulk-publish') }}">
                        @csrf
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th><input type="checkbox" id="selectAll"></th>
                                        <th>ID</th>
                                        <th>Student</th>
                                        <th>Exam</th>
                                        <th>Class</th>
                                        <th>Session</th>
                                        <th>Status</th>
                                        <th>Generated By</th>
                                        <th>Published At</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($admitCards as $admitCard)
                                    <tr>
                                        <td><input type="checkbox" name="ids[]" value="{{ $admitCard->id }}"></td>
                                        <td>{{ $admitCard->id }}</td>
                                        <td>{{ $admitCard->student->name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->exam->name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->student->class_name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->academic_session }}</td>
                                        <td>
                                            <span class="badge bg-{{ $admitCard->status == 'draft' ? 'secondary' : ($admitCard->status == 'published' ? 'success' : 'info') }}">
                                                {{ ucfirst($admitCard->status) }}
                                            </span>
                                        </td>
                                        <td>{{ $admitCard->generator->name ?? 'N/A' }}</td>
                                        <td>{{ $admitCard->published_at ? $admitCard->published_at->format('d M Y h:i A') : 'N/A' }}</td>
                                        <td>
                                            <a href="{{ route('admin.admit-cards.preview', $admitCard) }}" class="btn btn-sm btn-info">Preview</a>
                                            @if($admitCard->status === 'draft')
                                                <a href="{{ route('admin.admit-cards.publish', $admitCard) }}" class="btn btn-sm btn-success" onclick="return confirm('Are you sure you want to publish this admit card?')">Publish</a>
                                            @elseif($admitCard->status === 'published')
                                                <a href="{{ route('admin.admit-cards.lock', $admitCard) }}" class="btn btn-sm btn-warning" onclick="return confirm('Are you sure you want to lock this admit card?')">Lock</a>
                                                <a href="{{ route('admin.admit-cards.revoke', $admitCard) }}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to revoke this admit card?')">Revoke</a>
                                            @elseif($admitCard->status === 'locked')
                                                <a href="{{ route('admin.admit-cards.revoke', $admitCard) }}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to revoke this admit card?')">Revoke</a>
                                            @elseif($admitCard->status === 'revoked')
                                                <a href="{{ route('admin.admit-cards.publish', $admitCard) }}" class="btn btn-sm btn-success" onclick="return confirm('Are you sure you want to republish this revoked admit card?')">Republish</a>
                                            @endif
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="10" class="text-center">No admit cards found.</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>

                        @if(count($admitCards) > 0)
                        <div class="mt-3">
                            <button type="submit" class="btn btn-success" onclick="return confirm('Are you sure you want to publish selected admit cards?')">Bulk Publish</button>
                            <a href="{{ route('admin.admit-cards.bulk-lock', request()->query()) }}" class="btn btn-warning" onclick="return confirm('Are you sure you want to lock selected admit cards?')">Bulk Lock</a>
                            <button type="button" class="btn btn-danger" onclick="submitBulkRevoke()">Bulk Revoke</button>
                        </div>
                        <form method="POST" action="{{ route('admin.admit-cards.bulk-revoke') }}" name="bulkRevokeForm" id="bulkRevokeForm">
                            @csrf
                            <input type="hidden" name="ids" id="bulkRevokeIds">
                        </form>
                        <script>
                            function submitBulkRevoke() {
                                const checkboxes = document.querySelectorAll('input[name="ids[]"]:checked');
                                if (checkboxes.length === 0) {
                                    alert('Please select at least one admit card to revoke.');
                                    return;
                                }
                                if (confirm('Are you sure you want to revoke selected admit cards?')) {
                                    const ids = Array.from(checkboxes).map(cb => cb.value);
                                    document.getElementById('bulkRevokeIds').value = ids.join(',');
                                    document.getElementById('bulkRevokeForm').submit();
                                }
                            }
                        </script>
                        @endif
                    </form>

                    {{ $admitCards->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.getElementById('selectAll').addEventListener('click', function() {
    const checkboxes = document.querySelectorAll('input[name="ids[]"]');
    checkboxes.forEach(checkbox => checkbox.checked = this.checked);
});
</script>
@endsection
