<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle ?? 'Biometric Report' }} - Biometric Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-meta {
            margin-bottom: 20px;
            font-size: 12px;
        }
        .report-meta div {
            margin: 2px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .summary-row {
            font-weight: bold;
            background-color: #e6f3ff;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ $reportTitle ?? 'Biometric Report' }}</h2>
        <p>Generated on: {{ $generatedAt ?? now()->format('d-m-Y H:i:s') }}</p>
    </div>

    @if(isset($teacher))
    <div class="report-meta">
        <div><strong>Teacher:</strong> {{ $teacher->name }}</div>
        <div><strong>Teacher ID:</strong> {{ $teacher->id }}</div>
        <div><strong>Email:</strong> {{ $teacher->email }}</div>
        @if(isset($monthName))
            <div><strong>Month:</strong> {{ $monthName }}</div>
        @endif
    </div>
    @endif

    @if(isset($summary))
    <h3>Monthly Summary</h3>
    <table>
        <thead>
            <tr>
                <th>Total Days</th>
                <th>Present Days</th>
                <th>Attendance %</th>
                <th>Late Arrivals</th>
                <th>Early Departures</th>
                <th>Avg Working Hours</th>
                <th>Punctuality Score</th>
                <th>Discipline Score</th>
            </tr>
        </thead>
        <tbody>
            <tr class="summary-row">
                <td>{{ $summary['total_days'] }}</td>
                <td>{{ $summary['present_days'] }}</td>
                <td>{{ $summary['attendance_percentage'] }}%</td>
                <td>{{ $summary['late_arrivals'] }}</td>
                <td>{{ $summary['early_departures'] }}</td>
                <td>{{ $summary['avg_working_hours'] }}</td>
                <td>{{ $summary['punctuality_score'] }}%</td>
                <td>{{ $summary['discipline_score'] }}%</td>
            </tr>
        </tbody>
    </table>
    @endif

    @if(isset($records) && $records->count() > 0)
    <h3>Detailed Attendance Records</h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Day</th>
                <th>First In</th>
                <th>Last Out</th>
                <th>Working Hours</th>
                <th>Status</th>
                <th>Late Minutes</th>
                <th>Early Departure Minutes</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $record)
            <tr>
                <td>{{ $record->date->format('d-m-Y') }}</td>
                <td>{{ $record->date->format('l') }}</td>
                <td>{{ $record->first_in_time ? $record->first_in_time->format('H:i') : 'N/A' }}</td>
                <td>{{ $record->last_out_time ? $record->last_out_time->format('H:i') : 'N/A' }}</td>
                <td>{{ number_format($record->calculated_duration, 2) }}</td>
                <td>{{ ucfirst(str_replace('_', ' ', $record->status_badge['text'])) }}</td>
                <td>{{ $record->late_minutes ?? 0 }}</td>
                <td>{{ $record->early_departure_minutes ?? 0 }}</td>
                <td>{{ $record->remarks ?: 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p>No detailed records available for the selected period.</p>
    @endif

    <div class="footer">
        <p>Generated by HelpingHand School Management System</p>
        <p>Page <span class="page-number"></span> of <span class="page-count"></span></p>
    </div>
</body>
</html>